name: ambulance_tracking_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  # Map and Location packages
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  location: ^8.0.1
  geolocator: ^14.0.2
  http: ^1.1.2
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
